name: Deploy Ingestion to Cloud Run

on:
  push:
    branches:
      - feature/ingestion  # Change to 'main' later when you merge
    paths:
      - 'src/ingestion/**' # Only trigger if ingestion code changes

env:
  PROJECT_ID: "mike-personal-portfolio"
  REGION: "us-central1"
  REPO_NAME: "flash-crash-repo" 
  IMAGE_NAME: "ingestion-service"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Authenticate with Google Cloud using a GitHub Secret
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 2. Tell Docker to log into Google Artifact Registry
      - name: Configure Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 3. Build and push the container to Google Cloud
      - name: Build and Push
        run: |
          cd src/ingestion
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          docker build -t $IMAGE_PATH .
          docker push $IMAGE_PATH

      # 4. Deploy the continuous service to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          # 4. Deploy the continuous service to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          gcloud run deploy crypto-ingestion-service \
            --image $IMAGE_PATH \
            --region ${{ env.REGION }} \
            --cpu 1 \
            --memory 512Mi \
            --no-cpu-throttling \
            --min-instances 1 \
            --max-instances 1 \
            --set-env-vars PROJECT_ID=${{ env.PROJECT_ID }},TOPIC_ID=crypto-ticks